### ISSUE TITLE
Creating new image components

### ISSUE THREAD

**Issue by bronze** [Princesseuh/astro-eleventy-img#2] opened 2022-02-08 02:51 UTC
Hi

Im trying to create a new component so i can pass different options, following your markdownimage example.
But im getting an error about the lack of renderers
```
Unable to render BackgroundImage!

There are no `renderers` set in your `astro.config.mjs` file.
```

any tips on this?

**Comment by Princesseuh** [comment] 2022-02-08 07:33
Hmm, just like that I'm not too sure. This error usually happens when Astro can't render the component, often because of a missing dependency or an import not working

Do you have an example of code or a reproduction on Stackblitz (or similar) I could look at?

**Comment by bronze** [comment] 2022-02-08 15:59
yes, i was trying it out at one of my repos: https://stackblitz.com/github/bronze/digitalcanvas-com-br
trying to insert an image at index.astro

**Comment by Princesseuh** [comment] 2022-12-15 02:39
Closing since this is very old and the Astro error handling around there has changed a lot since

**Closed by Princesseuh** 2022-12-15 02:39 UTC
